name: Gardena Smart by RK
version: 0.1.15
slug: gardena_smart_by_rk
description: Gardena Smart System helpers
arch: [aarch64, amd64]
startup: services
boot: auto
ingress: false
options:
  app_key: ""
  app_secret: ""
  git_repo: ""
schema:
  app_key: str
  app_secret: str
  git_repo: str
