name: NB Boknedlaster by RK
version: 0.1.15
slug: nb_boknedlaster_by_rk
description: Download books from NB.no as PDF with OCR and TOC
arch: [aarch64, amd64]
startup: application
boot: auto
ingress: false
options:
  book_id: ""
  chapters: []
  output: "/config/www/nb/output.pdf"
  digitalarkivet_enabled: false
  digitalarkivet_endpoint: ""
  git_repo: ""
schema:
  book_id: str
  chapters:
    - str
  output: str
  digitalarkivet_enabled: bool
  digitalarkivet_endpoint: str
  git_repo: str
