name: System Dump by RK
version: 0.1.11
slug: system_dump_by_rk
description: Dumps system info for debugging
arch:
  - amd64
  - aarch64
startup: once
boot: manual
ingress: false
options:
  output_path: "/config/system_dump.txt"
  git_repo: ""
schema:
  output_path: str
  git_repo: str
