name: System Dump by RK
version: 0.1.15
slug: system_dump_by_rk
description: Dumps system info for debugging
arch: [aarch64, amd64]
startup: services
boot: auto
ingress: false
options:
  output_path: "/config/system_dump.txt"
  git_repo: ""
schema:
  output_path: str
  git_repo: str
