name: POS Backend by RK
version: 0.1.11
slug: pos_backend_by_rk
description: POS backend with Google Sheets integration, stock, sales, labels
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
ports:
  "8091/tcp": 8091
ingress: false
options:
  google_sheet_id: ""
  service_account_json: "/config/pos_service_account.json"
  ha_event: "pos_sale"
  git_repo: ""
schema:
  google_sheet_id: str
  service_account_json: str
  ha_event: str
  git_repo: str
webui: "http://[HOST]:[PORT:8091]"
