name: Tuya Local by RK
version: 0.1.15
slug: tuya_local_by_rk
description: Local Tuya utilities
arch: [aarch64, amd64]
startup: services
boot: auto
ingress: false
options:
  devices: []
  git_repo: ""
schema:
  devices:
    - str
  git_repo: str
