name: Tuya Local by RK
version: 0.1.11
slug: tuya_local_by_rk
description: Local Tuya utilities
arch:
  - amd64
  - aarch64
startup: services
boot: auto
ingress: false
options:
  devices: []
  git_repo: ""
schema:
  devices:
    - str
  git_repo: str
